apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatify-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatify
  template:
    metadata:
      labels:
        app: chatify
    spec:
      containers:
      - name: chatify
        image: vtheofil1/chatify:v1.0
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: chatify-secret
              key: DATABASE_URL
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: chatify-secret
              key: SESSION_SECRET
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
