version: '3.9'

services:
  db:
    image: postgres:15
    container_name: chat_db
    restart: always
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: chatify_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://chatuser:admin123@db:5432/chatdb
    env_file:
      - .env

volumes:
  pgdata:
